### ISSUE TITLE
Open dialog pops up on un-minimize and desktop switch

### ISSUE THREAD

**Issue by alexforencich** [jcelaya/hdrmerge#100]
Open dialog pops up and takes focus when HDRmerge is un-minimized or when the desktop is switched.

**Comment by Beep6581** [comment]
@alexforencich which version of HDRMerge, which OS, which window manager, how did you un-minimize it, etc... http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports

**Comment by alexforencich** [comment]
Sorry.  Latest version from git, on Arch Linux with XFCE, un-minimized by clicking on the corresponding window button on the panel or alt+tab.

**Comment by alexforencich** [comment]
Looks like you're unconditionally showing the open dialog when the window show event occurs.  Changing this to only display the dialog when the image stack is empty solves this issue.
