### ISSUE TITLE
Batch with fixed number of photos instead of gap? May skip long exposures in gap.

### ISSUE THREAD

**Issue by photographer-mememe** [jcelaya/hdrmerge#102]
Is it possible to batch with a fixed number of photos?
When using gap, some sets could be mixed up or missing.

For example I do longer exposures for panorama photos using fisheye.
To get 360 degrees I shoot 4 set of 3 bracketed images, total 12 images.
(with hundreds of images in a shooting).

So when doing one panorama (12 images), for example I shoot first set -3ev 0ev +3ev, maybe 6, 2, 1/2 second.
Then I turn the camera and after 4 seconds press the shutter button.  I shoot again 6, 2, 1/2 seconds. Repeat 2 more times. Total 12 images.

Using batch command with gap, it is impossible to set a gap to correctly select the sets.  Gap between each set is only 3 seconds, but the longest exposure is 6 seconds.

If I set batch gap 6 seconds, all 12 photos will be merged.  If I set 3 seconds, then the 6 second exposure will always skip and only 2 images will be merged in each set instead of 3 images.

Only possibility is to wait more than 6 seconds before shooting next set.
But if the longest exposure is 30 or 60 seconds, then I have to wait 1 minute before I can press the shutter button again.

**Comment by Beep6581** [comment]
I shoot the same way, but I move all photos from each panorama into their own folder and run HDRMerge in batch mode on that folder, no gap. The two seconds it takes to create a folder and move the relevant photos into it is less than the time it takes figuring out the ideal gap and dealing with false positives. Would that not work better for you?

If not, then how exactly should such a feature work, to not include photos which are not in your panorama but in the same folder?

**Comment by photographer-mememe** [comment]
I decided to use Lightroom.  I was trying out HDRMerge because Lightroom doesn't have a batch function.  But I'm getting noise in the black with HDRMerge 0.5.  I checked the mask, it's solid on the black.  In Lightroom it's noiseless.  In HDRMerge I had to push up the DNG to +4.5ev, while in Lightroom I set it to +1.33 ev to get the same result.  I don't know if this has something to do with the black noise in HDRMerge.

So I found a way to script Lightroom with Autohotkey.  It was actually pretty simple but took me several hours to figure out.  Sort the library by rating.  Set all photos to 0 rating.  Set filter to RAW only, Unrated only, then select the first image on top left corner.  Run this Autohotkey script and press Ctrl 8.

What happens is shift right right will select 3 brackets.  Then press CTRL SHIFT H to start the merge.  Wait a few seconds, rate the 3 RAW as 5 star.  Since filter is set to unrated, the 3 RAW will drop to the bottom of the library (sort by rating) and disappear.  The first unrated RAW on top left is automatically selected.  Code will loop again.
`^8::
	Sleep, 1000
	Loop, 4
	{
		IfWinNotActive, catalog6 - Adobe Photoshop Lightroom - Library
		{
			break
		}
		Send, {SHIFTDOWN}{RIGHT}{RIGHT}{SHIFTUP}{CTRLDOWN}{SHIFTDOWN}h{CTRLUP}{SHIFTUP}
		Sleep, 4900
		Send, 5
		Sleep, 3500
	}
return`

**Comment by Beep6581** [comment]
> I decided to use Lightroom. I was trying out HDRMerge because Lightroom doesn't have a batch function. But I'm getting noise in the black with HDRMerge 0.5. I checked the mask, it's solid on the black. In Lightroom it's noiseless. In HDRMerge I had to push up the DNG to +4.5ev, while in Lightroom I set it to +1.33 ev to get the same result. I don't know if this has something to do with the black noise in HDRMerge.

Can't say with certainty without seeing the raw files in question, but probably not a HDRMerge problem as Lightroom denoises photos even when denoising is disabled.

**Comment by photographer-mememe** [comment]
In my HDRMerge DNG I was also getting black banding on things like a black chair.  I think it's similar to the issue with the white banding that I saw on the issues list.
