### ISSUE TITLE
decodeFPDeltaRow() license?

### ISSUE THREAD

**Issue by LebedevRI** [jcelaya/hdrmerge#103]
@jcelaya  Hi.
What is the license of `decodeFPDeltaRow()` function in https://github.com/Beep6581/RawTherapee/blob/880d0305486d8d9f6a4bb71c9f42a45921bfe48e/rtengine/dcraw.patch#L3173-L3183 ?
I'm being suggested to use it in LGPL2 library, https://github.com/darktable-org/rawspeed/pull/17

**Comment by jcelaya** [comment]
MIT License, copyright 2014 Javier Celaya <jcelaya@gmail.com>

Thanks for asking :)

**Comment by LebedevRI** [comment]
Thank you.
