### ISSUE TITLE
Batch process

### ISSUE THREAD

**Issue by Teddy2017** [jcelaya/hdrmerge#104]
Hi, 
I am not a programmer, and I need to use the batch process to make HDR . 
The option -a -B are not work. In theory, yes, will work, but in fact, no., 
Please, if do you know how to write the command line syntax  for batch HDR, will appreciate. 

Example:
I put my .dnf (or .nef) files in the folder named "D:\test". 

How must look like the command line to make HDR on 24 bits
 (each set of photos was made with 3 stops:-2/0/+2 EV). 

Thank you, in advance!

(please test if works before add a comm)

**Comment by Beep6581** [comment]
Works fine.

```
$ ls *.arw
test_1.arw  test_2.arw  test_3.arw
$ ~/programs/hdrmerge-master/hdrmerge --batch *.arw
Writing /tmp/test_1-3.dng, 16-bit, 6024x4024
```

Upload a bracketed set using https://filebin.net/ if you would like me to try with your files.

**Comment by Teddy2017** [comment]
Ok, 
Thank you!

Please tell me: 
You put all .nef files into a folder - Example: D\test,  and, then what command line do you type on cmd.exe?

Here is my photos:
http://fastupload.rol.ro/32f3231082e1f02dde394abeac6b9a7e.html

https://filebin.net/ - run too slow...

**Comment by Beep6581** [comment]
@Teddy2017 I can't unpack rar files, and that website looks dodgy. It put your rar files in a zip file and included spam. If you want me to take a look, please put the photos in a libre compressed format such as zip, 7-zip, bz2, etc., and upload using https://filebin.net/

**Comment by Teddy2017** [comment]
https://filebin.net/jl09lrcnlb6jz3v2

**Comment by muntzstudios** [comment]
@Beep6581  - For give my extremely basic question haha, but how in the world do you launch a batch processing action with HDRMerge? I open terminal and type what? I'm very new to this (command line stuff) but desperately want to be able to use this to batch out DNG Hdrs in a more efficient manner rather than creating them all in LR

**Comment by Beep6581** [comment]
@muntzstudios navigate to the folder with your photos, then run hdrmerge with the `--batch` flag and your raw photo extension as an argument. For example, if your photos have a `.dng` extension:
```
cd /home/muntz/photos
hdrmerge --batch *.dng
```

**Comment by muntzstudios** [comment]
Is there a way to make this automatic, with automator? Thanks so much for your help!

**Comment by muntzstudios** [comment]
Hi Beep6581 - I’m trying to run this, but it’s saying no command found? 

I dragged my folder into the terminal, so I get the exact location, then added the cd in front of it (with the space, as I see below) but can’t get the hdrmerge app to batch

Any suggestions?

**Comment by muntzstudios** [comment]
I’ve managed to figure out how to run the batch functionality. All images are 2 stops apart from one and other and within a 5 bracket interval. The final result looks terrible, the images have a lot of pink color over certain parts of it. How can I fix this? Is it some sort of a settings issue?

**Comment by Beep6581** [comment]
As I wrote above, this is not the place for user support.

**Comment by muntzstudios** [comment]
Ok, how is someone supposed to get support or help with this?

**Comment by Beep6581** [comment]
@muntzstudios 

> I see you've cross-posted in the forum, so keep further user-support questions in the forum.
