### ISSUE TITLE
hdrmerge appears to write wrong tag type for NewSubfileType

### ISSUE THREAD

**Issue by LebedevRI** [jcelaya/hdrmerge#105]
```
0x00fe Exif.SubImage1.NewSubfileType                SLong       1   4  0  Primary image
```
it should be LONG.
Yet the code [appears](https://github.com/jcelaya/hdrmerge/blob/8bd6e7f199ec3e55206715ef5ca44aee5df5a983/DngFloatWriter.cpp#L241) to write it correctly.

The sample is https://raw.pixls.us/getfile.php/883/raw/hdrmerge-bayer-fp32-w-pred-deflate.dng
Converted from https://raw.pixls.us/getfile.php/771/raw/5G4A9394.CR2
using 
```
0x0131 Exif.Image.Software                          Ascii      16  16  HDRMerge v0.5.0  HDRMerge v0.5.0
```
which i think is 8e652a1b17e989e372682bae6fecc4a72fce8312

**Comment by heckflosse** [comment]
@LebedevRI Why do you think 8e652a1 is related?

**Comment by LebedevRI** [comment]
i was speaking about the version that i believe i used when generating the dng

**Comment by heckflosse** [comment]
It's written [here](https://github.com/jcelaya/hdrmerge/blob/master/ExifTransfer.cpp#L173).

**Comment by LebedevRI** [comment]
Aha!
So i guess that should be `0u`.

**Comment by LebedevRI** [comment]
Thank you.
Though It's interesting that ${adobe dng validity checker} program did not complain
(i did not check)
