### ISSUE TITLE
HDRMerge : Unable to open .dng file

### ISSUE THREAD

**Issue by SyedAzha** [jcelaya/hdrmerge#106]
![capture1](https://cloud.githubusercontent.com/assets/28474772/25770243/18c351fe-3263-11e7-84af-4ea44cffdcad.PNG)
Here is a link to that RAW file:
https://filebin.net/p28u363y6ch3tbv1
All other programs like lightroom, photoshop, and Camera RAW can open it. So, I'm sure there is nothing wrong with the file.

**Comment by heckflosse** [comment]
That's an already demosaiced DNG file. HDRMerge works on undemosaiced data only.

**Comment by SyedAzha** [comment]
Is there a way to undemosaic such .dng files

**Comment by Beep6581** [comment]
No.
