### ISSUE TITLE
Mac Command Line

### ISSUE THREAD

**Issue by carsonaberle** [jcelaya/hdrmerge#116]
I was able to get the hdr merge built from the develop branch on High Sierra 10.13.3 and run a merge on 5 .dng files. The program looks great, but for batch processing I would like to be able to use the command line for this. Is this currently possible, if not, it would be a nice feature.

**Comment by heckflosse** [comment]
@carsonaberle From [here](https://github.com/jcelaya/hdrmerge/blob/master/README.md)

```
The program can also be run without GUI, in batch mode. This is accomplished either by providing an output file name with the "-o" switch, or by generating an automatic one with the "-a" switch. Other switches control the output parameters, refer to the output of the "--help" switch.
```

**Comment by carsonaberle** [comment]
I was able to get the batch mode to work on Ubuntu, but not on Mac. I get the error hdrmerge: Command not found

**Comment by heckflosse** [comment]
@carsonaberle Sorry, as I don't own a Mac, I'm lost here

**Comment by Beep6581** [comment]
@carsonaberle provide your full build log and full output when you run HDRMerge from the console.
`cd` to the folder which contains the executable and try:
```bash
./hdrmerge --help
```
or
```bash
open -a hdrmerge --args --help
```

**Comment by carsonaberle** [comment]
It looks like i needed to run it form within the folder that contains the executable. In my case that was `/Applications/hdrmerge.app/Contents/MacOS`

Thank you for your help.

**Comment by Beep6581** [comment]
I added a note:
https://github.com/jcelaya/hdrmerge/commit/4bd5b4a018153858af7ed5b7f3c24808c1878076
