### ISSUE TITLE
Migrate to Qt5

### ISSUE THREAD

**Issue by Beep6581** [jcelaya/hdrmerge#123]
I migrated HDRMerge to Qt5 in the `qt5` branch.
Compilation status:
- [x] Linux
- [x] Windows
- [x] macOS

@Hombre57 @Benitoite would be great if you could update the CMake file so that it compiles in Windows and macOS.

You can compare changes between the `qt5` branch and `master` to get an idea of what changed and what changes you may need to make to the appropriate sections:
https://github.com/jcelaya/hdrmerge/compare/qt5

**Comment by Benitoite** [comment]
@Beep6581 CMakeLists.txt and test/CMakeLists.txt for mac build updates proposed: PR https://github.com/jcelaya/hdrmerge/pull/124

Mac build instructions are updated for branch qt5: https://github.com/jcelaya/hdrmerge/issues/56#issuecomment-372105553

One thing I noticed was the images/ (contains the mac bundle icon) is not present in this branch.

**Comment by Beep6581** [comment]
@Benitoite `images` is moved to `data\images`
https://github.com/jcelaya/hdrmerge/tree/qt5/data/images

**Comment by Benitoite** [comment]
@Beep6581 Thanks, updated. 😁

**Comment by Hombre57** [comment]
@jcelaya @Beep6581 See PR #128 for building on Windows. Now this is the good one !

There's still a problem when starting HDRMerge on Windows (don't know for others platform) : the "Open raw images" window size is something like 80x40px at first, you have to resize it.

Moreover it is not themed :disappointed: 

![non-themed hdrmerge - win64](https://user-images.githubusercontent.com/13788115/37931843-31842f9a-3147-11e8-931f-6001ba74c4d2.png)

**Comment by Beep6581** [comment]
HDRMerge `master` branch now requires Qt5.
