### ISSUE TITLE
MacOS, how to batch in command line

### ISSUE THREAD

**Issue by nongrata23** [jcelaya/hdrmerge#125]
Hello, first of all i am very happy that i found this software.. 
I have a challange if you can please provice me a workflow to undestand better how to do batch mode in command line,

i mean were should i put the files, also how to the command line would look? i understoot that the separation is made by time btw images.

because this is not enough ./hdrmerge -B, i did try with others but i m new to this.
Thank you

Regards

**Comment by Beep6581** [comment]
@nongrata23 upload a few sample images using https://filebin.net/

**Comment by nongrata23** [comment]
Hello, for example those files....

https://filebin.net/h4zvint6jim1wl4c

Thank you

**Comment by Beep6581** [comment]
@nongrata23 here's an example. I compiled HDRMerge into `~/programs/hdrmerge` though if you installed it system-wide you don't need to specify the path. I recommend setting the output file to 16-bit with a half-sized preview, as is the case in this example. You can also remove the `--no-align --no-crop` part.
```bash
~/programs/hdrmerge/hdrmerge --batch -b 16 -p half --no-align --no-crop *.NEF
```

**Comment by nongrata23** [comment]
Thank you so much is working!
