### ISSUE TITLE
Not compatible with anything?

### ISSUE THREAD

**Issue by enzyme69** [jcelaya/hdrmerge#130]
I produce the DNG by merging a couple of DNG RAW photos taken using iPhone. Once it merged, I cannot actually open the file in Apple Photos, LuminanceHDR, etc. 

Is there something that I did wrong? Like when exporting in 16, 24, 32, none seems to work either.

**Comment by Beep6581** [comment]
Use a program which is capable of reading floating-point DNG files, such as RawTherapee.
