### ISSUE TITLE
Open and Save dialogs have no sidebar URLs

### ISSUE THREAD

**Issue by Hombre57** [jcelaya/hdrmerge#135]
As you can see below, there's no side URLs in the Open and Save dialog. Even if you disable the code that adds an entry to this list, it's still empty.

![hdrm-no-side-urls](https://user-images.githubusercontent.com/13788115/39470118-2994a97a-4d3c-11e8-8e35-13f5ffce362f.png)

@heckflosse Do you confirm on your side ? @Beep6581 is it the same on Linux ?

**Comment by Floessie** [comment]
@Hombre57 Same on Debian 9.4 (XFCE).

**Comment by Beep6581** [comment]
Same in Sabayon, `continuous-5-g`00bda2f.

**Comment by Beep6581** [comment]
QT4 load:
![imgur-2018_05_01-14 40 28](https://user-images.githubusercontent.com/5844619/39473222-056ae9ee-4d4e-11e8-9b47-6e9a7fa5c1f7.png)

QT4 save:
![imgur-2018_05_01-14 40 53](https://user-images.githubusercontent.com/5844619/39473227-0a325f02-4d4e-11e8-92b6-48019105e8bd.png)

**Comment by Beep6581** [comment]
http://doc.qt.io/qt-5/qfiledialog.html#getOpenFileNames
http://doc.qt.io/qt-5/qfiledialog.html#Option-enum

```diff
diff --git a/src/LoadOptionsDialog.cpp b/src/LoadOptionsDialog.cpp
index 1751e8b..3e9370d 100644
--- a/src/LoadOptionsDialog.cpp
+++ b/src/LoadOptionsDialog.cpp
@@ -140,7 +140,7 @@ void LoadOptionsDialog::addFiles() {
     ")"));
     QStringList files = QFileDialog::getOpenFileNames(this, tr("Open raw images"),
         lastDirSetting.isNull() ? QDir::currentPath() : QDir(lastDirSetting.toString()).absolutePath(),
-        filter, NULL, QFileDialog::DontUseNativeDialog);
+        filter, Q_NULLPTR, Q_NULLPTR);
     if (!files.empty()) {
         QString lastDir = QFileInfo(files.front()).absolutePath();
         settings.setValue("lastOpenDirectory", lastDir);
diff --git a/src/MainWindow.cpp b/src/MainWindow.cpp
index 4cb219d..8ad7d79 100644
--- a/src/MainWindow.cpp
+++ b/src/MainWindow.cpp
@@ -351,7 +351,6 @@ void MainWindow::saveResult() {
         urlsBak = saveDialog.sidebarUrls();
         urls << urlsBak << QUrl::fromLocalFile(io.getInputPath());
         saveDialog.setSidebarUrls(urls);
-        saveDialog.setOptions(QFileDialog::DontUseNativeDialog);
 
         if (saveDialog.exec()) {
             QString file = saveDialog.selectedFiles().front();
```

![imgur-2018_05_01-14 52 36](https://user-images.githubusercontent.com/5844619/39473551-ae24a16e-4d4f-11e8-9b23-8ffc839cc2e5.png)

**Comment by heckflosse** [comment]
@Hombre57 

> Do you confirm on your side

I never built hdrmerge on windows

**Comment by gaaned92** [comment]
@Beep6581 
 Thanks for the patch

![screen-2018-06-09_10-49-52](https://user-images.githubusercontent.com/13785581/41189751-feccb696-6bd2-11e8-8b2b-669fe30cd535.jpg)




> HDRmerge_master_continuous-22-g757f3c4_release_64.zip

uploaded at
https://keybase.pub/gaaned92/LHDR64/

**Comment by Beep6581** [comment]
@Hombre57 do you remember what was the issue with the patch above?

**Comment by Hombre57** [comment]
@Beep6581 IIRC, on Win7, clicking on "Open" didn't closed the file selector. I've updated my MSYS2 toolchain, and it works fine now, though we end up with Windows' file selector, where we can't add entry in the url side bar. :+1:  to commit

**Comment by Beep6581** [comment]
Hopefully someone who knows Qt comes along and helps out.
https://discuss.pixls.us/t/do-you-know-your-way-around-qt-help-needed/8027

**Comment by gaaned92** [comment]
@Hombre57  could you explain please what you mean by 

 `though we end up with Windows' file selector, where we can't add entry in the url side bar.`
 as I don't notice something missing for windows10?

**Comment by Beep6581** [comment]
@gaaned92 for example we can't add the current photo's folder to the sidebar when using the save dialog.

**Comment by Beep6581** [comment]
@Hombre57 @Floessie could you try this patch on top of latest master?
```diff
diff --git a/src/LoadOptionsDialog.cpp b/src/LoadOptionsDialog.cpp
index 3e9370d..1751e8b 100644
--- a/src/LoadOptionsDialog.cpp
+++ b/src/LoadOptionsDialog.cpp
@@ -140,7 +140,7 @@ void LoadOptionsDialog::addFiles() {
     ")"));
     QStringList files = QFileDialog::getOpenFileNames(this, tr("Open raw images"),
         lastDirSetting.isNull() ? QDir::currentPath() : QDir(lastDirSetting.toString()).absolutePath(),
-        filter, Q_NULLPTR, Q_NULLPTR);
+        filter, NULL, QFileDialog::DontUseNativeDialog);
     if (!files.empty()) {
         QString lastDir = QFileInfo(files.front()).absolutePath();
         settings.setValue("lastOpenDirectory", lastDir);
diff --git a/src/MainWindow.cpp b/src/MainWindow.cpp
index ae23a9f..90ffdd7 100644
--- a/src/MainWindow.cpp
+++ b/src/MainWindow.cpp
@@ -344,6 +344,7 @@ void MainWindow::saveResult() {
         }
 
         QFileDialog saveDialog(this, tr("Save DNG file"), name, tr("Digital Negatives (*.dng)"));
+        saveDialog.setOptions(QFileDialog::DontUseNativeDialog);
         saveDialog.setAcceptMode(QFileDialog::AcceptSave);
         saveDialog.setFileMode(QFileDialog::AnyFile);
         saveDialog.setConfirmOverwrite(true);
```
Create a HDR DNG using raw files from an unusual location, like `~/foo/bar<1-3>.raw` or `c:\not my documents\potatos\bar<1-3>.raw`
Ctrl+s to save, and see if `~/foo/` or `c:\not my documents\potatos\` are in the sidebar.

**Comment by gaaned92** [comment]
Create a HDR DNG using raw files from an unusual location, like ~/foo/bar<1-3>.raw or c:\not my documents\potatos\bar<1-3>.raw
Ctrl+s to save, and see if ~/foo/ or c:\not my documents\potatos\ are in the sidebar.

**Comment by Beep6581** [comment]
Both suite my needs so I don't really have a favorite, but if I had to choose I'd vote for non-native, where the source folder appears at the top.

**Comment by gaaned92** [comment]
@Beep6581 on W10
- Master branch
see my post above.
 When saving , the folder used for opening raws is indicated by default. You can create new folder. OK for me 
- qfiledialog-not native. 
As you described above. I don't have standard locations for photos as they are dispatched in specific folders. So I think it's less interesting than Master

So I vote for Master branch
Thank you for improvment.

**Comment by Beep6581** [comment]
@gaaned92 @Hombre57 and others, when testing, please show a screenshot of the Save window as it looks like when using `master` or `qfiledialog-notnative`, and state your OS (and window manager if Linux).
When using master, make sure you're on commit ba22dc8 (or newer).
Make sure that your source photos are in a non-standard location, for example create c:\blah and put the source photos into that.

**Comment by Hombre57** [comment]
@Beep6581 After some search in the doc and on the web, I think it's normal that the side bar urls is empty. It's its default state. I'm making a patch to add standard urls. Will come back shortly...

**Comment by Beep6581** [comment]
The current implementation adds the following URLs to the sidebar which should not be there (tested in Sabayon):
* run
* boot
* efi
* 1000

If anyone knows how to fix that, a patch would be welcome.

**Comment by Hombre57** [comment]
@Beep6581 By looking at the mount list you pasted on IRC, `efi` seem to be your Windows partition and `1000` your temp mount.

**Comment by Beep6581** [comment]
@Hombre57 yes,
* `efi` seems to be the Windows bootloader (the folder is owned by root and its `rwx------` so only root can list contents),
* `1000` is a tmpfs but different to `/tmp`, owned by me,
* `boot` and `run` are owned by root but anyone can look inside but not write.
and none of those locations folders appear in any other program.

I also noticed that custom sidebar locations are not saved between HDRMerge sessions, that would be nice to have.
