### ISSUE TITLE
Allow to specify the number of bracketed photos per set

### ISSUE THREAD

**Issue by nongrata23** [jcelaya/hdrmerge#146]
Hello, is it possible to set by command the number of brakets instead exif time, because i am using a mobile and the exif is wrong... so i cannot batch

any ideeas?

thank you

**Comment by nongrata23** [comment]
i found a temporary solution to manually fix the exif in the files, i can edit the exif date with xmpview, and i made a macro for each 3 sets to have a close time and a 5seconds gap... still would be nice the option to set the number of brakets..

Thanks best software

**Comment by fanckush** [comment]
just for information, this PR #168 adds this feature
