### ISSUE TITLE
Tooltips should appear over all image icons and show the image filename

### ISSUE THREAD

**Issue by Beep6581** [jcelaya/hdrmerge#148]
The colored square image icons in the toolbar have tooltips which show the EV value. The tooltip does not appear for the darkest image - it is implied that it's 0EV, but in my opinion it should explicitly show that.
Furthermore, it would be useful if the tooltips showed the filename of the image they apply to.

**Comment by Beep6581** [comment]
And here I thought I was going to have to spend months plowing through fields of fire and thorns to figure out how to implement this myself, when a gift falls from the heavens... :)
I will test after work!

**Comment by Floessie** [comment]
Small gifts preserve friendships. :smile:

**Comment by Beep6581** [comment]
@Floessie it works very well, +1 for commit/PR :)

**Comment by Floessie** [comment]
@Beep6581 Your wish is my command. :wink:

**Comment by Beep6581** [comment]
12 hours - what a life! ;)
