### ISSUE TITLE
Corrupt result merging Pentax K10D PEFs

### ISSUE THREAD

**Issue by Beep6581** [jcelaya/hdrmerge#151]
I'm quite sure these images were easily mergeable in the past, but now the result has vertical striped artifacts.

http://rawtherapee.com/shared/test_images/amsterdam_moving_boat_1.pef
http://rawtherapee.com/shared/test_images/amsterdam_moving_boat_2.pef
http://rawtherapee.com/shared/test_images/amsterdam_moving_boat_3.pef

![screenshot_20180619_153850](https://user-images.githubusercontent.com/5844619/41600872-48a34d50-73d7-11e8-9ea6-4b19ef41c889.png)
![screenshot_20180619_154128](https://user-images.githubusercontent.com/5844619/41600873-48defe18-73d7-11e8-958a-e62f3e0739b1.png)

**Comment by heckflosse** [comment]
Confirmed

**Comment by Floessie** [comment]
Should be fixed with b3ba8209d3bb78b76a2221d0164a702056efa8a5.

**Comment by Beep6581** [comment]
Confirmed.
