### ISSUE TITLE
Unable to run batch properly 

### ISSUE THREAD

**Issue by muntzstudios** [jcelaya/hdrmerge#187]
I've followed everyone's steps, reviewed everything I can find currently online... and I'm still having issues with running a batch functionality with this software via a command line.

1) it's running at 16 bit, and I can't seem to figure out how to change it to 32 bit with the flag? When I input the command, it does literally nothing. 
2) I ran it successfully, it created the DNG files, but they are a bit messed up. I see a lot of pink and weirdness in the shadows. Does that have something to do with not being in 32bit? 
3) I deleted the files, and was attempting to run the command again, in order to recreate the files and now it won't run at all. I've followed the same commands as before, nothing. Will it only process once per folder? Is there some sort of history? 

Appreciate the help (if this isn't the place to post this, where should I post this? please share the correct URL)

**Comment by Beep6581** [comment]
Closing, as this was cross-posted in the forum and the sample images provided in the forum were batch-processed using the latest dev without issues.

Please don't cross-post, and use the forum for user support.
