### ISSUE TITLE
"Error converting the preview to JPEG: Unsupported image format"

### ISSUE THREAD

**Issue by akidee** [jcelaya/hdrmerge#204]
I get this error for all images of my batch. The DNG is valid, but the preview is missing.

`hdrmerge -B -g 5 -b 16 -p full -vv -a *_{0..3}.dng`

    [  0%] Loading IMG_20200811_153234_0.dng
    IMG_20200811_153234_0.dng: 4032x3024 (4032x3024+0+0, by samsung SM-G930F, 64ISO 1/3200sec f1.7 EV:-13.8188
    e1e1e1e1 RGBG, sat 1023, black 0, flip 0, wb: 1.77778 1 1.43619 0, cblack: 0 0 0 0
    [ 25%] Loading IMG_20200811_153234_2.dng
    IMG_20200811_153234_2.dng: 4032x3024 (4032x3024+0+0, by samsung SM-G930F, 64ISO 1/50sec f1.7 EV:-7.81878
    e1e1e1e1 RGBG, sat 1023, black 0, flip 0, wb: 1.77778 1 1.43619 0, cblack: 0 0 0 0
    [ 50%] Loading IMG_20200811_153234_1.dng
    IMG_20200811_153234_1.dng: 4032x3024 (4032x3024+0+0, by samsung SM-G930F, 64ISO 1/400sec f1.7 EV:-10.8188
    e1e1e1e1 RGBG, sat 1023, black 0, flip 0, wb: 1.77778 1 1.43619 0, cblack: 0 0 0 0
    Load files: 0.364607 seconds
    [ 75%] Aligning
    Image 1 displaced to (4, -2) with error 251619
    Image 0 displaced to (4, -8) with error 224756
    Align: 0.19597 seconds
    Compute response functions: 0.155091 seconds
    Generate mask: 0.429508 seconds
    [100%] Done loading!
    Writing result to /Users/andi/Pictures/eigene/chronologisch/2020/2020-08-11/IMG_20200811_153234_0-2.dng
    Writing /Users/andi/Pictures/eigene/chronologisch/2020/2020-08-11/IMG_20200811_153234_0-2.dng, 16-bit, 4028x3016 cropped
    [  0%] Rendering image
    Adjusted white balance: 1.77778 1 1.43619 1
    Fatten mask: 0.216571 seconds
    Blur: 1.08811 seconds
    Compose: 0.659695 seconds
    [ 33%] Rendering preview
    Render preview: 3.30597 seconds
    [ 66%] Writing output
    Error converting the preview to JPEG: Unsupported image format
    Write output: 2.66845 seconds
    [100%] Done writing!

**Comment by heckflosse** [comment]
Duplicate of https://github.com/jcelaya/hdrmerge/issues/192 ?

**Comment by akidee** [comment]
Correct, this issue didn't show up when I searched for it.
