### ISSUE TITLE
Thank you very much for the program!

### ISSUE THREAD

**Issue by mrkaban** [jcelaya/hdrmerge#205]
Thank you very much for the program under a free open source license! I added your program to the Russian-language site about free software, here is the [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D0%BA%D0%B0/%D0%BF%D1%80%D0%BE%D1%87%D0%B5%D0%B5/hdrmerge-hdr-from-raw.html).

Please do not leave the program, this is a very interesting project!

**Comment by alexmyczko** [comment]
What about a new release though?

**Comment by Beep6581** [comment]
A new release is made when these issues are resolved:
https://github.com/jcelaya/hdrmerge/milestone/5
