### ISSUE TITLE
Release 8 years ago...

### ISSUE THREAD

**Issue by alexmyczko** [jcelaya/hdrmerge#220]
...would it not be a good time to release 0.6 sometime soon? And check/process current PRs?

**Comment by gitoss** [comment]
Any 0.6x-ish Windows binary would be very welcome, no matter if it's an official release. The old binary links in the Issues seem to be all dead...

**Comment by alexmyczko** [comment]
You want it? You fork it!

**Comment by FliiFe** [comment]
I agree with the original issue, and forking isn't exactly an option here when trying to package this. A quick glance at the repology page linked to in the README should be enough to convince anyone that this versioning isn't exactly practical.

Even a v0.6.0-rc1 or similar tag would be greatly appreciated and would help packaging on various linux distributions.

**Comment by FliiFe** [comment]
Is there a specific reason this issue was closed ?

**Comment by alexmyczko** [comment]
@FliiFe i doubt anything will happen. i intend to orphan the package in debian and remove it…
