### ISSUE TITLE
Constant exposure

### ISSUE THREAD

**Issue by Beep6581** [jcelaya/hdrmerge#37]
When I shoot 360° panoramas I do so on manual mode with bracketing, e.g. a bracketed set of 5 images every 60°, so 6x5 . The files produced by HDRMerge however differ in their average exposure - some need a +1EV boost in RawTherapee, others need even +4EV. Would it be possible to lock a constant exposure so that a common point visible in several or all of the resulting HDR DNG images, such as a floor tile, has the same brightness?

**Comment by Blizzara** [comment]
Hi! I asumme this was never implemented? At least I think I hit the same problem. I'm thinking of trying to implement this myself, so I was wondering if you @jcelaya had some concrete idea on how to do this?

**Comment by jcelaya** [comment]
Maybe you can go through all the images on a first run, find the most exposed one, and use it to scale down all the DNGs in relation to their apperture/speed/ISO. I don't see an obvious solution here.
