### ISSUE TITLE
DNG turns out black

### ISSUE THREAD

**Issue by Beep6581** [jcelaya/hdrmerge#52]
Hi, I encountered another set of images that lead to a black DNG using today's git:
http://filebin.net/d3es9h8z5t (uploading, done in 10 minutes)

**Comment by Beep6581** [comment]
Unfortunately I do not have these images I uploaded anymore, but if I encounter the problem again I will let you know.

**Comment by t-o-d-d** [comment]
DrSlony asked that I share some images which reproduce this issue, so here they are... I found that removing either of the dark exposures would then cause an image to appear, but with all five loaded, blank. http://1drv.ms/1GK7fjH

**Comment by jcelaya** [comment]
OK, It looks like I finally fixed this. It's in the develop branch, as usual, can you check it? Thanks everyone.

**Comment by jcelaya** [comment]
Forget that last commit, it is still wrong...

**Comment by t-o-d-d** [comment]
I wanted to check the last one for you but don't know how to compile it 
or whatever needs to happen to update my install (on windows)...
Todd

On 3/28/2015 2:42 AM, jcelaya wrote:
>
> Forget that last commit, it is still wrong...
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/jcelaya/hdrmerge/issues/52#issuecomment-87198108>.
>



---
This email has been checked for viruses by Avast antivirus software.
http://www.avast.com

**Comment by Beep6581** [comment]
Javier I see all your comments and I'm grateful for your work, the only reason I haven't responded is because I currently don't have any source photos which exhibited this problem so I could test, and the links above have expired. I tend to convert my bracketed raws to HDR DNG and then delete the source images to save a lot of disk space.

**Comment by jcelaya** [comment]
Thanks for your comments. I just pushed some new commits to the develop branch that should fix the problem with the black images and improve the color tints in the blown out areas.

Todd, I can confirm that your last pictures do not produce a black DNG anymore. I will submit a 0.5.1 version when I get some more feedback. Thanks again for all your comments.

**Comment by KyleTheHacker** [comment]
Javier: are we going to see this 0.5.1 at some point? ^^

**Comment by Beep6581** [comment]
Closing as Javier wrote that he fixed the issue, the filebin is expired, and I haven't noticed this problem in a long time.

A new release will be made soon.
