### ISSUE TITLE
Hard transitions

### ISSUE THREAD

**Issue by Beep6581** [jcelaya/hdrmerge#6]
I'm really hoping that the issues I see are fixable, because there is enormous potential here!

So far on all shots I tried - Pentax K10D with manual or automatic lenses - I see very hard transitions where different source images were used.
http://i.imgur.com/QSkBBxd.jpg
http://i.imgur.com/xEIca0P.jpg

The colors in that house were very difficult as there was a sunlight with yellow glass camera-left, and the big window downstairs, plus other light sources and unlit areas (this is from a panorama, so it's only about 1/30th of the whole).
http://i.imgur.com/O1wq05z.png
HDRMerge with RawTherapee does a fantastic job if not for the hard transitions, and if invisible transitions were possible it would be a kickass solution! 

See the large blobs on the ceiling and walls:
http://i.imgur.com/THloiua.jpg
http://i.imgur.com/j4tS6rF.jpg

I'm uploading a few bracket series here, some of the shots are from the Samyang manual lens without aperture info, so currently they won't work unless you use exiftool or make HDRMerge not rely on Exif :) The files should be up in 15 minutes. http://filebin.net/j5lo3p3s6m

**Comment by Beep6581** [comment]
Hey again!

I still run into this once in a while, but I learned to work around it, by removing the darkest images.

Today I ran into this issue again in a merge of three images. However in this case, the darkest image contains data in the highlights which is clipped in the middle image, so I need to use all three, yet I also get this hard transition in the top-left corner.
You can get the images and the HDR DNG created with 0.5.0 with the problem here:
http://filebin.net/b0w1sw908k
The link will expire in a year.

**Comment by jcelaya** [comment]
I think this problem is similar to ghosting, but with light. Look at the upper left corner, for instance. Its brightness is similar to the rest of the ceiling in the middle image, but in the bright one all the ceiling is blown out but that corner. I'm still not sure how to fix this, though...

**Comment by Beep6581** [comment]
The links have expired, the issues are mostly fixed, and the code changed significantly since 2015.
Closing.
