### ISSUE TITLE
Do HDR DNGs contain a thumbnail?

### ISSUE THREAD

**Issue by Beep6581** [jcelaya/hdrmerge#63]
Hey

This issue is specifically about thumbnails (small), not embedded previews (large, medium, or none).

I tested now using the latest git version of HDRMerge. I saved a DNG using a medium-resolution preview.

  exiftool -b -ThumbnailImage hdrmerge.dng > foo.jpg
  exiv2 -et hdrmerge.dng

Both commands fail to get a thumbnail image. Exiftool-9.90 produces a 0-byte file, and exiv2-0.24-r1 prints "hdrmerge.dng: Image does not contain an Exif thumbnail".

1- Do these DNGs contain a thumbnail when saving with a medium or large preview size?
2- Do these DNGs contain a thumbnail when saving with no preview?
3- Where is the thumbnail stored if it exists?
4- How does one extract them with exiv2 and exiftool?

Kind regards

**Comment by jcelaya** [comment]
Nope, no thumbnail.
