### ISSUE TITLE
Artifacts in highlights

### ISSUE THREAD

**Issue by heckflosse** [jcelaya/hdrmerge#71]
When merging this files
http://www.rawtherapee.com/shared/test_images/blue_sky_tree_drslony_bkt1.pef
http://www.rawtherapee.com/shared/test_images/blue_sky_tree_drslony_bkt2.pef
http://www.rawtherapee.com/shared/test_images/blue_sky_tree_drslony_bkt3.pef
hdrmerge generates some bright artifacts.
http://filebin.net/9qwv2ybk1c/artifacts.png
This https://github.com/heckflosse/hdrmerge/commit/49cbeae8678ba170de14bbb6c35700dcb89a2799 fixes it.

Ingo

**Comment by Beep6581** [comment]
Fix confirmed.

**Comment by jcelaya** [comment]
Nice, thank you

**Comment by heckflosse** [comment]
Ok, I didn't see that you already fixed the bug in develop branch. Great.
