### ISSUE TITLE
Coloured artifacts when wrong white level (satThreshold) is used

### ISSUE THREAD

**Issue by heckflosse** [jcelaya/hdrmerge#72]
When merging files of my D700 I often get greenish artifacts in bright regions. These are caused by hdrmerge using a white level (satThreshold) of 16383, which is to high for D700 files. I made a try with a hard coded satThreshold of 15800 and the artifacts are gone. I vote for adding a possibility somewhere in hdrmerge gui to override the white level or using https://github.com/Beep6581/RawTherapee/blob/master/rtengine/camconst.json , which would be an even better solution...

Here are two example dng files with white level of 16383 and white level of 15800

http://filebin.net/dprf4en3ir

Ingo

**Comment by t-o-d-d** [comment]
Great to see you guys working on this app! I hope it means an updated 
version someday that non-coders like myself could use... I use the 
current windows version quite a bit. Wish I knew how to compile!
Todd

On 9/22/2015 4:39 AM, heckflosse wrote:
>
> When merging files of my D700 I often get greenish artifacts in bright 
> regions. These are caused by hdrmerge using a white level 
> (satThreshold) of 16383, which is to high for D700 files. I made a try 
> with a hard coded satThreshold of 15800 and the artifacts are gone. I 
> vote for adding a possibility somewhere in hdrmerge gui to override 
> the white level or using 
> https://github.com/Beep6581/RawTherapee/blob/master/rtengine/camconst.json 
> , which would be an even better solution...
>
> Here are two example dng files with white level of 16383 and white 
> level of 15800
>
> http://filebin.net/dprf4en3ir
>
> Ingo
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/jcelaya/hdrmerge/issues/72>.
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by heckflosse** [comment]
@t-o-d-d : As you I'm also on Win64. But for hdrmerge (and for some other stuff) I use Linux in a virtual machine. The 0.5.0 windows64 version of hdrmerge is quite slow. I currently don't know why but it's not using all (8) cores of my machine. On Linux the master branch makes much better use of the 8 cores (though it does not include changes which could be responsible for the better performance). Can you confirm (by looking at the task manager) that behaviour on your win64 system?

Ingo

**Comment by heckflosse** [comment]
I pushed a change to my fork: https://github.com/heckflosse/hdrmerge/commit/d3b43850fc1627163d8bf2a250982f67ea4d1e48

**Comment by heckflosse** [comment]
For reference : http://filebin.net/v186jfz97z

http://filebin.net/v186jfz97z/d700_hdrmerge_wl16383.png shows a detail of merged result using libraw white level of 16383
http://filebin.net/v186jfz97z/d700_hdrmerge_wl15800.png shows the same detail of merged result using custom white level 15800

Above link contains all files (source files, merged files and screenshots)

Ingo

**Comment by t-o-d-d** [comment]
I only have a dual core I3 processor... Gets me by because of 16GB ram 
and an SSD drive, but yeah, far behind you in CPU capacity.

So I don't know how to tell if it's using 1 or 2 cores in the task 
manager. I only see one service under processes. It's at about 12 megs 
of memory and then when I run a merge of five DNG files, it runs at 
about 50% CPU until they are merged... It's not unbearably slow for me...

Todd

On 9/22/2015 4:24 PM, heckflosse wrote:
>
> @t-o-d-d <https://github.com/t-o-d-d> : As you I'm also on Win64. But 
> for hdrmerge (and for some other stuff) I use Linux in a virtual 
> machine. The 0.5.0 windows64 version of hdrmerge is quite slow. I 
> currently don't know why but it's not using all (8) cores of my 
> machine. On Linux the master branch makes much better use of the 8 
> cores (though it does not include changes which could be responsible 
> for the better performance). Can you confirm (by looking at the task 
> manager) that behaviour on your win64 system?
>
> Ingo
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/jcelaya/hdrmerge/issues/72#issuecomment-142451461>.
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by heckflosse** [comment]
@t-o-d-d 

I just made a test using the files from here http://filebin.net/v186jfz97z :

1) using hdrmerge 0.5.0 on Win64 (8 cores available for hdrmerge):
Load files: 0.7846 seconds
Compute response functions: 1.24016 seconds
Generate mask: 0.057508 seconds
Fatten mask: 0.053506 seconds
Blur: 0.305039 seconds
Compose: 0.099513 seconds
Render preview: 8.01702 seconds
Write output: 0.656583 seconds


2) using my fork on Linux (same machine, but assigned only 4 cores to Linux)

Load files: 0.250212 seconds
Compute response functions: 0.280445 seconds
Generate mask: 0.0620339 seconds
Fatten mask (SSE version): 0.0129852 seconds
Blur: 0.131768 seconds
Compose: 0.0739482 seconds
Render preview: 0.266903 seconds
Write output: 0.489228 seconds

**Comment by heckflosse** [comment]
@t-o-d-d : Use hdrmerge.com --vv for timing and hdrmerge.com --help for command line switches.

ingo

**Comment by heckflosse** [comment]
Done with 6b79263
