### ISSUE TITLE
the .dng output is not readable 

### ISSUE THREAD

**Issue by kalmarek** [jcelaya/hdrmerge#74]
I use the 0.5.0 version (but tried the git-master as well).

Steps to reproduce:
1. open test/sample[1-3].dng files
2. save output (as dng)
3. try to open the saved file (with hdrmerge, or other)

Neither hdrmerge nor darktable can read the output file (which is not really strange, they use the same libraw)

here is the file:
https://dl.dropboxusercontent.com/u/2158899/sample1-3.dng

I suspect some peculiarity of my system(s?), as this is quite important feature ;-) and nobody reported the behaviour I experience. However, I was able to reproduce it on a completely different machine (using different flavour of Linux)

versions of libs:
libraw-0.16.2
exiv2-0.24
zlib-1.2.8
qt-4.8.6
alglib-3.8.2
(this is from my Gentoo stable, but also reproducible on up-to-date Arch)

cheers,

**Comment by heckflosse** [comment]
https://dl.dropboxusercontent.com/u/2158899/sample1-3.dng openes fine in RawTherapee

**Comment by abulak** [comment]
I've just tried opening it in RawTherapee: it works.

Why can't hdrmerge open its own output??

**Comment by heckflosse** [comment]
Why should it? It's made to merge integer raw files into a float raw file. Once this is done, there's nothing to do for hdrmerge.
Though the main reason is that it uses libraw. RawTherapee uses a modified dcraw (which thanks to Javier is able to read all the float dng files).
IIRC DarkTable can read 32bit float dng. Maybe you can try this?

Ingo

**Comment by abulak** [comment]
Thanks for Your answers; for future searches: libraw can not read float dngs

https://github.com/LibRaw/LibRaw/issues/39

**Comment by sl2va** [comment]
I have problem with processing dng
https://yadi.sk/i/XhH80AzMjwFwT
It's dng file from raw video sequence (5d mark ii). After processing in hdrmerge 0.5.0 dng file don't open in lightroom (RawTherapee open). But file from still mode (.cr2), open in lightroom fine.

P.S  abulak – I can open your dng in lightroom. https://dl.dropboxusercontent.com/u/2158899/sample1-3.dng

**Comment by CarVac** [comment]
Is there any way to make HDRMerge output optimally-dithered 16-bit integer DNGs that LibRaw would be able to read?

AKA even if the bracketing is such that the deep shadows have too little noise to dither, add gaussian noise with a standard deviation of 1/2 of an LSB so as to eliminate banding?

It's either that, or having the RawTherapee team spin out its raw loading facilities into a library for my photo editor, since LibRaw won't be supporting float anytime soon...

**Comment by Beep6581** [comment]
LibRaw supports floating-point DNGs:
https://github.com/LibRaw/LibRaw/issues/39#issuecomment-240998284
