### ISSUE TITLE
Unable to load Pentax .PEF files

### ISSUE THREAD

**Issue by milescrawford** [jcelaya/hdrmerge#80]
I am unable to load images from my Pentax K-S1 on Mac OS X.  All attempts show a dialog that says cannot open image, and the following is printed to the terminal:
/Users/mcrawfor/Desktop/IMGP1723.PEF: data corrupted at 160290

Here is the RAW file in question (zipped so github allows upload):
[IMGP1723.PEF.zip](https://github.com/jcelaya/hdrmerge/files/96444/IMGP1723.PEF.zip)

This is version 0.5.0 of HDRMerge, I'm running OSX 10.10.5

**Comment by FM33** [comment]
I just succeed opening it with the current version I just build today on Ubuntu 16.04 amd64.
