### ISSUE TITLE
I've created a Fedora RPM

### ISSUE THREAD

**Issue by djotaku** [jcelaya/hdrmerge#81]
Hey there jcelaya,

I'm not sure if you're still working on this since there don't seem to be updates for a year, but I created an RPM so that Fedora users could install without having to compile. The copr repository is at https://copr.fedorainfracloud.org/coprs/djotaku/hdrmerge/

Also, I had to patch it because Fedora does not put alglib in any of your search paths.

**Comment by heckflosse** [comment]
@djotaku https://discuss.pixls.us/t/hdrmerge-status-update/2009

**Comment by Beep6581** [comment]
@djotaku when v1.0 is released soon, could you update the RPM and post instructions on how to install it, including how to get your repo?

**Comment by Beep6581** [comment]
@djotaku is your RPM maintained?
https://copr.fedorainfracloud.org/coprs/djotaku/hdrmerge/
```text
hdrmerge
Build: 582556
State: failed
Finished: 11 months ago
```

**Comment by fanckush** [comment]
Should this be removed from v1.0 milestone? maybe pushed to 1.1?

**Comment by Beep6581** [comment]
Actually, as there's been no response in ages, I'm closing this.

**Comment by djotaku** [comment]
hey, not sure about milestones, but I have made it work now for F29

**Comment by luzpaz** [comment]
Could you submit it to Fedora Rawhide, so it could show up on repology?    
[![Packaging status](https://repology.org/badge/vertical-allrepos/hdrmerge.svg)](https://repology.org/project/hdrmerge/versions)

**Comment by djotaku** [comment]
> Could you submit it to Fedora Rawhide, so it could show up on repology?
> [![Packaging status](https://camo.githubusercontent.com/2318429c22cfec536174be75cdf865c56b48924b/68747470733a2f2f7265706f6c6f67792e6f72672f62616467652f766572746963616c2d616c6c7265706f732f6864726d657267652e737667)](https://repology.org/project/hdrmerge/versions)

Sure, but there hasn't been a release in a long time. Can we get a new official release? Then I can create a new release.

**Comment by djotaku** [comment]
> @djotaku is your RPM maintained?
> https://copr.fedorainfracloud.org/coprs/djotaku/hdrmerge/
> 
> ```
> hdrmerge
> Build: 582556
> State: failed
> Finished: 11 months ago
> ```

Sorry about that - I wasn't properly getting updates from GH at the time and missed it. As of May 15 I have it working again for F29.
