### ISSUE TITLE
Can't see thumbnails files in open dialog box

### ISSUE THREAD

**Issue by engardeknave** [jcelaya/hdrmerge#83]
HDRMerge uses a non-standard open dialog (at least in Windows) that doesn't allow the viewing of image thumbnails. This makes it very difficult to choose the correct files. It's necessary to open up Windows Explorer to find the files, remember the names/numbers, then finally select all the files needed. It would be much better just to use a standard Windows open dialog in which the views can be changed to even large previews.

Because the application starts with an open dialog that has no thumbnails, one must switch tasks to Explorer to find the files. But since the application only consists of an open dialog at this point, with no main window, it does not yet have a taskbar icon. So as soon as it loses focus, it falls behind other windows and cannot be found until everything else is minimized. It would be better to show the main window and then, optionally at that point, pop up an open dialog box.

**Comment by Beep6581** [comment]
Handled in #135
