### ISSUE TITLE
Ok to link to the forum at pixls.us?

### ISSUE THREAD

**Issue by patdavid** [jcelaya/hdrmerge#89]
Hi Javier (et al)!

Before I issue a PR I wanted to check and see if it was ok if I added links to the forum for HDRMerge on pixlsus (https://discuss.pixls.us/c/software/hdrmerge) to the README.md and the index page (on gh-pages)?

**Comment by jcelaya** [comment]
I see no problem


Javi

2016-08-29 17:54 GMT+02:00 Pat David <notifications@github.com>:
