### ISSUE TITLE
HDRmerge unable to open file

### ISSUE THREAD

**Issue by KarlTheKangaroo** [jcelaya/hdrmerge#93]
For some reason, when I try to merge HDRs, the program tells me that it is unable to open a certain file.
![troubleshoot for hdrmerge](https://cloud.githubusercontent.com/assets/22183685/18495897/f5769340-7a53-11e6-8e47-586de20f0fd7.PNG)
Cheers

**Comment by Beep6581** [comment]
You need to upload the raw files for us to try and reproduce. Use https://filebin.net/

**Comment by KarlTheKangaroo** [comment]
@Beep6581 https://filebin.net/4m20torflbtq30zy

**Comment by heckflosse** [comment]
Those are jpg files with wrong ending.

**Comment by KarlTheKangaroo** [comment]
@Beep6581 @heckflosse Thanks guys, stupid mistake :P I uploaded them onto google drive and downloaded them again which might be the root of the problem.
