### ISSUE TITLE
Add a link to hdrmerge appimage in readme.md

### ISSUE THREAD

**Issue by heckflosse** [jcelaya/hdrmerge#95]
As soon as the hdrmerge appimage build using latest hdrmerge master and libraw code is available, we should add a link to the appimage in readme.md

**Comment by Beep6581** [comment]
Yes, I'll take care of it. I'll do it either when the AppImage uses the latest libraw(-beta), or when it is announced that using the latest libraw beta is not possible (for whatever reason).

**Comment by Beep6581** [comment]
Done in https://github.com/jcelaya/hdrmerge/tree/treeclean#download--installation

**Comment by probonopd** [comment]
I did not find an AppImage download link at the link given above - am I blind? ;-)

**Comment by Beep6581** [comment]
> Download & Installation
Find the latest builds on our releases page.

The AppImage will be there with the next release, if the AppImage script still works.
