### ISSUE TITLE
Contributor list

### ISSUE THREAD

**Issue by heckflosse** [jcelaya/hdrmerge#96]
I would like to make a list of hdrmerge contributors like the one [we have in RawTherapee](https://github.com/Beep6581/RawTherapee/blob/master/AUTHORS.txt) and show them in hdrmerge/about window. 
Any objections?

Ingo

**Comment by Beep6581** [comment]
That's standard practice, +1

**Comment by jcelaya** [comment]
+1


Javi

2016-09-19 8:56 GMT+02:00 Beep6581 <notifications@github.com>:
