### ISSUE TITLE
Export to 16-bit & 32-bit TIFF

### ISSUE THREAD

**Issue by joegiampaoli** [jcelaya/hdrmerge#99]
What about exporting to high bit TIFF (16 - 32 bit float) so other programs can open the merged HDR output?

Thanks for a great program...

**Comment by Beep6581** [comment]
The DNG is not demosaiced, it's raw. For the TIFF to be usable by other software, it would need to be demosaiced. That can be done by opening the raw DNG in for example RawTherapee, with far greater control than HDRMerge would allow.
